apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
  - port: {{ .Values.ServicePort }}
    targetPort: {{ .Values.port }}
